# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    schedule:
      interval: "weekly"
    groups:
      mui:
        patterns:
          - "@mui/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      emotion:
        patterns:
          - "@emotion/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
